name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: can-bridge-2port
            path: Software/CANBRIDGE-2port/source
            out_file: can-bridge-firmware
            toolchain: arm
          - name: can-bridge-3port
            path: Software/CANBRIDGE-3port/leaf-can-bridge-3-port
            out_file: can-bridge-firmware
            toolchain: avr

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install ARM GCC Toolchain
        if: matrix.toolchain == 'arm'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi make

      - name: Install AVR GCC Toolchain
        if: matrix.toolchain == 'avr'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-avr avr-libc make

      - name: Compile Firmware (${{ matrix.name }})
        working-directory: ${{ matrix.path }}
        run: make all

      - name: Convert HEX to BIN (ARM)
        if: matrix.toolchain == 'arm'
        run: arm-none-eabi-objcopy -I ihex -O binary ${{ matrix.path }}/build/${{ matrix.out_file }}.hex ${{ matrix.out_file }}.bin

      - name: Convert HEX to BIN (AVR)
        if: matrix.toolchain == 'avr'
        run: avr-objcopy -I ihex -O binary ${{ matrix.path }}/${{ matrix.out_file }}.hex ${{ matrix.out_file }}.bin

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}-firmware
          path: ${{ matrix.out_file }}.bin
          if-no-files-found: error
          retention-days: 7

  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    permissions:
      contents: write # Required to create a release
    steps:
      - name: Download all firmware artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-files

      - name: Rename firmware files
        run: |
          for dir in release-files/*; do
            if [ -d "$dir" ]; then
              mv "$dir"/*.bin "release-files/$(basename "$dir").bin"
            fi
          done

      - name: Create and Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ github.sha }}
          name: Release ${{ github.sha }}
          generate_release_notes: true
          files: release-files/*.bin